import "../styles/globals.css";
import Link from "next/link";
import Head from "next/head";
import styles from "../styles/Home.module.css";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Pokémon again</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ul className={styles.list}>
        <li className={styles.description}>
          <Link href="/">
            <a>Home</a>
          </Link>
        </li>
        <li className={styles.description}>
          <Link href="/pokemon">
            <a>Pokémon</a>
          </Link>
        </li>
        <li className={styles.description}>
          <Link href="/mypokemon-ssr">
            <a>My Pokémon SSR</a>
          </Link>
        </li>
        <li className={styles.description}>
          <Link href="/mypokemon-ssg">
            <a>My Pokémon SSG</a>
          </Link>
        </li>
        <li className={styles.description}>
          <Link href="/mypokemon-isr">
            <a>My Pokémon ISR</a>
          </Link>
        </li>
      </ul>
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
